### ISSUE TITLE
Add Location services

### ISSUE THREAD

**Issue by pattisonmichael** [Ludy87/xplora_watch#1]
Hello! Very Cool project, I was just looking at doing the same :)
Do you have plans to add the location services to the integration any time soon?
Otherwise I might take a stab at it in the next few days when I find time.

**Comment by Ludy87** [comment]
Hi thanks.
Yes, I have planned, but I don't know how to implement it, if you can give me a tip, that would be okay.

**Comment by pattisonmichael** [comment]
I got a first version almost working, hopefully i find some time tomorrow to send a PR.

**Comment by pattisonmichael** [comment]
#2

**Comment by Ludy87** [comment]
add: https://github.com/Ludy87/xplora_watch/releases/tag/0.0.10
