### ISSUE TITLE
Hi, then I'm trying to install it I'm getting an error Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Ludy87** [Ludy87/xplora_watch#116]
Hi, then I'm trying to install it I'm getting an error Config flow could not be loaded: {"message":"Invalid handler specified"}

What I'm doing wrong?

_Originally posted by @NoLifer88 in https://github.com/Ludy87/xplora_watch/discussions/89#discussioncomment-4243044_

**Comment by Ludy87** [comment]
Hi @NoLifer88 describe how you proceed.

**Comment by NoLifer88** [comment]
Home assistant installed on dietpi. But everything else from HACS I can install without any problems. When I press +integration and choose Xplora I see this error

**Comment by Ludy87** [comment]
Please give more information https://my.home-assistant.io/redirect/system_health/

**Comment by NoLifer88** [comment]
Don't know why, but this link not working for me. Probably need to install it like OS but found some info in logs  Logger: homeassistant.config_entries
Source: config_entries.py:810
First occurred: 3:09:14 PM (2 occurrences)
Last logged: 8:42:18 PM

Error occurred loading configuration flow for integration xplora_watch: No module named 'dataclasses_json'

**Comment by Ludy87** [comment]
The link leads to system information `Settings -> System -> Repairs -> top right three dots -> System information`

**Comment by NoLifer88** [comment]
## System Information

version | core-2022.11.4
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | false
python_version | 3.9.15
os_name | Linux
os_version | 5.15.76-v7l+
arch | armv7l
timezone | Europe/London
config_dir | /mnt/dietpi_userdata/homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4975
Installed Version | 1.28.3
Stage | running
Available Repositories | 1151
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 20, 2022 at 3:14 PM
-- | --
current_recorder_run | November 26, 2022 at 3:05 PM
estimated_db_size | 22.58 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

**Comment by Ludy87** [comment]
Try installing version v2.5.2 to see what happens.

**Comment by NoLifer88** [comment]
Thank you. Managed to install it. Trying to log in now
