### ISSUE TITLE
Device Tracker Unique ID

### ISSUE THREAD

**Issue by kentivar** [Ludy87/xplora_watch#12]
Any way to add Unique ID to the device tracker? so i can edit the device tracker entity id in ui?! :)

**Comment by Ludy87** [comment]
Hi
the entity has a unique id, it is not editable. There is currently no way to change that.

**Comment by kentivar** [comment]
Ok, i tried changing the entity id created by the integration, but home assistant are saying it does not have an unique id so it cannot be changed in ui :)

**Comment by Ludy8687** [comment]
Yes the behavior is correct, but it doesn't affect the function in any way. I haven't found any technology that can change that.

**Comment by Ludy8687** [comment]
Yes the behavior is correct, but it doesn't affect the function in any way. I haven't found any technology that can change that.

**Comment by Ludy87** [comment]
Yes the behavior is correct, but it doesn't affect the function in any way. I haven't found any technology that can change that.
