### ISSUE TITLE
Denmark +45

### ISSUE THREAD

**Issue by kai74** [Ludy87/xplora_watch#14]
Hi
I would love it if you would make this possible to be used in Denmark

I have tested to set up everything, but I get an error in the log

Logger: homeassistant.components.device_tracker
Source: custom_components/xplora_watch/device_tracker.py:69 
Integration: Device tracker (documentation, issues) 
First occurred: 8:01:50 PM (1 occurrences) 
Last logged: 8:01:50 PM

Error setting up platform legacy xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 251, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(
  File "/config/custom_components/xplora_watch/device_tracker.py", line 69, in async_setup_scanner
    for safeZone in await controller.getSafeZones_async(id):
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 397, in getSafeZones_async
    raise Exception('Xplora API call finally failed with response: ')
Exception: Xplora API call finally failed with response: 

Best regards Kai

**Comment by Ludy87** [comment]
Hi, can you control the watch with the Xplora app?
https://play.google.com/store/apps/details?id=com.xplora.xplorao2o

The support release comes from Xplora itself, otherwise check the phone number you entered. This must be registered once in the app and exist as a contact.

**Comment by kai74** [comment]
Yes it is working with the app.
The mobile number is now added as contact, but exactly the same error
message..

Something else we can test?

Best regards Kai

**Comment by kai74** [comment]
Hi

Found the problem I needed to add some Safe zone. Now it is working fine.

best regards Kai

Den ons. 16. feb. 2022 kl. 07.52 skrev Kai Bråthen ***@***.***>:

> Yes it is working with the app.
> The mobile number is now added as contact, but exactly the same error
> message..
>
> Something else we can test?
>
> Best regards Kai
>

**Comment by Ludy87** [comment]
thanks for your feedback, have fun
