### ISSUE TITLE
🐛 xplora X5 play does not show sensors

### ISSUE THREAD

**Issue by gig0r0** [Ludy87/xplora_watch#141]
### What version of Integration has the issue?

V2.5.6

### System Health details

Informationen zum System
Version	core-2023.1.2
Installationstyp	Home Assistant OS
Entwicklung	false
Supervisor	true
Docker	true
Benutzer	root
Virtuelle Umgebung	false
Python-Version	3.10.7
Betriebssystemfamilie	Linux
Betriebssystem-Version	5.15.76-v8
CPU-Architektur	aarch64
Zeitzone	Europe/Berlin
Konfigurationsverzeichnis	/config
Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
GitHub API Calls Remaining	4793
Installed Version	1.29.1
Stage	running
Available Repositories	1271
Downloaded Repositories	18
Home Assistant Cloud
Angemeldet	true
Ablauf des Abonnements	9. Januar 2023 um 01:00
Relais verbunden	true
Remote aktiviert	false
Remote verbunden	false
Alexa aktiviert	true
Google aktiviert	true
Remote-Server	eu-central-1-0.ui.nabu.casa
Zertifikatsserver erreichbar	ok
Authentifizierungsserver erreichbar	ok
Home Assistant Cloud erreichbar	ok
Home Assistant Supervisor
Host-Betriebssystem	Home Assistant OS 9.4
Update-Channel	stable
Supervisor-Version	supervisor-2022.12.1
Agent-Version	1.4.1
Docker-Version	20.10.19
Speicherplatz gesamt	57.8 GB
Speicherplatz genutzt	25.6 GB
Gesund	true
Unterstützt	true
Board	rpi4-64
Supervisor-API	ok
Versions-API	ok
Installierte Add-ons	Z-Wave JS (0.1.74), Studio Code Server (5.5.1), Terminal & SSH (9.6.1), Node-RED (14.0.1), Duck DNS (1.15.0), Let's Encrypt (4.12.7), ESPHome (2022.12.3)
Dashboards
Dashboards	2
Ressourcen	2
Ansichten	10
Modus	storage
Recorder
Älteste Startzeit der Ausführung	1. Januar 2023 um 20:11
Aktuelle Startzeit der Ausführung	9. Januar 2023 um 10:39
Geschätzte Datenbankgröße (MiB)	1733.05 MiB
Datenbank-Engine	sqlite
Datenbankversion	3.38.5

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

State of all sensors, except Xcoin, is "unknown".
![image](https://user-images.githubusercontent.com/109808419/211283672-4878b98a-32a0-4f1d-8911-bf91967a7a1c.png)

![image](https://user-images.githubusercontent.com/109808419/211283734-0277c1d7-7625-401b-b307-6965aa229694.png)

![image](https://user-images.githubusercontent.com/109808419/211286157-a312b62d-aa42-44cd-84a0-b500e8201919.png)

### Reproduction steps

Added watch via email login. 

### Debug logs

```text
Logbuch
9. Januar 2023
xxx Watch Message xxx wurde unbekannt
08:40:21 - Vor 3 Stunden
xxx Watch State xxx wurde getrennt
08:40:21 - Vor 3 Stunden
xxx Watch Safezone xxx war unsicher
08:40:21 - Vor 3 Stunden
xxx Watch Charging xxx wurde unbekannt
08:40:21 - Vor 3 Stunden
xxx Watch Tracker xxx wurde bei unknown erkannt
08:40:21 - Vor 3 Stunden
xxx Watch Message xxx nicht mehr verfügbar
08:38:12 - Vor 3 Stunden
```

**Comment by Ludy87** [comment]
Hi @gig0r0 wenn du dich in der App mit der Email Adresse anmeldest, hast du dann vollen Zugriff?

**Comment by gig0r0** [comment]
Hi @Ludy87,

ja. Gerade auf der App noch einmal abgemeldet und wieder neu angemeldet. Dort sehe ich dann alles.

**Comment by Ludy87** [comment]
Hast du einen Neustart versucht?
Den debugger aktivert? Bitte dann den log hier posten, Danke.

**Comment by gig0r0** [comment]
Alles probiert. habe das Plugin auch noch einmal komplett neu installiert.
Kann ich das Log privat zukommen lassen? Da ist ja die Uhren ID und Name usw. enthalten.

**Comment by Ludy87** [comment]
Hi, ja kannst du mir auch per Mail schicken, Adresse findest du hier: https://www.astra-g.org/datenschutz-2017/

**Comment by gig0r0** [comment]
Hi,
hab es via Mail geschickt. Was mir auch aufgefallen ist: Anmeldung via Telefonnummer hat nicht funktioniert. Nur via E-Mail.

**Comment by Ludy87** [comment]
Hi,

im log ist zusehen, dass der Xplora-Server mal wieder nicht erreichbar war.

Wenn es mit der Telefonnummer geklappt hat, dann wird die ein Fehler angezeigt, welche Meldung wird dort angezeigt?

**Comment by gig0r0** [comment]
Verbindung fehlgeschlagen

**Comment by Ludy87** [comment]
Wird dein Netzwerk durch einen piHole oder der Gleichen überwacht/gefiltert?

**Comment by gig0r0** [comment]
Oh. Ja! Ich schalte mal ab.

**Comment by gig0r0** [comment]
piHole DNS ist jetzt nicht mehr in Benutzung. Zur Sicherheit auch IPv6 mal in home assistant ausgeschaltet. 
Das gleiche Ergebnis.

**Comment by Ludy87** [comment]
Versuche bitte mal die Seite aufzurufen: https://api.myxplora.com/api

**Comment by gig0r0** [comment]
![image](https://user-images.githubusercontent.com/109808419/211751339-7ffc56f9-3684-4b89-af48-9f74a9778439.png)

**Comment by gig0r0** [comment]
wobei das 400 bad request ja auch im api output über den browser kommt.

**Comment by Ludy87** [comment]
Ja, okay das klappt.

Ich will nur die Fehlerquellen einschränken.

**Comment by Ludy87** [comment]
Kannst du noch einmal versuchen dich einzuloggen und kannst du mir dann noch mal den Log schicken?

**Comment by gig0r0** [comment]
Ich habe endlich mein Home Assistant Yellow bekommen. Der hat gerade ein plain HA, noch ohne Zeugs drumherum laufen. Da teste ich das xplora plugin auch mal.

**Comment by gig0r0** [comment]
Hat nichts gebracht. Aber hier der log output beim login:
![image](https://user-images.githubusercontent.com/109808419/211754913-3e0baf4c-11fd-406e-a232-9c03ad59aac1.png)

**Comment by gig0r0** [comment]
Um eine Fehlbedienung meinerseits auszuschließen, das gebe ich ein:
![image](https://user-images.githubusercontent.com/109808419/211756626-93ce8b08-1ec2-4646-92ea-cdc785b74430.png)
Telefonnummer ist die des Admin Accounts, was ich auch so in der App eingebe. Sonderzeichen im Passwort ein Problem?

**Comment by Ludy87** [comment]
Hört sich gut an,  jetzt haben wir das Problem gefunden.
Nun liegt es wohl am Passwort selber, kannst du sichergehen, dass du es korrekt eingegeben hast? Ansonsten müsste ich wissen ob es an den Sonderzeichen liegt.

**Comment by gig0r0** [comment]
Ich hab es gerade noch einmal auf der App probiert. Bin deshalb sicher. Ich hab aus dem Ausrufezeichen mal ein Punkt gemacht. Funktioniert auch nicht. Ein Sonderzeichen ist Pflicht.

**Comment by Ludy87** [comment]
Versuche es mit einem Bindestrich.

**Comment by gig0r0** [comment]
Hab - . @ probiert. Hab - auch mal vom Ende zur Mitte geschoben. Hilft alles nicht.

**Comment by Ludy87** [comment]
Dein Passwort hat min. 8 Zeichen, hat mind. 1 Groß- und Kleinbuchstaben, 1 Zahl und ein Sonderzeichen?

**Comment by gig0r0** [comment]
Mein Passwort hat derzeit genau genommen ein Großbuchstabe, mehrere kleine Buchstaben, vier Zahlen und ein Sonderzeichen. ;)

**Comment by Ludy87** [comment]
Ist sehr eigenartig, ich muss das Test, eventuell ist es doch noch ein anderer Fehler.

Ich werde die Tage die Lib Anpassen, denn eigentlich hat die Fehlermeldung noch einen zusätzlichen Kommentar, der in deiner Meldung fehlt.

**Comment by gig0r0** [comment]
Alles klar. Falls Hilfe benötigt wird, bin ich bereit.

**Comment by Ludy87** [comment]
Hi, ich habe jetzt mehrere hundert Passwörter ausprobiert und es wurden alle akzeptiert.

**Comment by gig0r0** [comment]
Hi,

ich habe jetzt echt ein echt ganz einfaches Passwort ala "Wort-1234" probiert. Es geht nicht. Gerade auch mal geschaut, was passiert, wenn ich eine andere Rufnummer angebe, da sagt er direkt "nicht registriert", mit der richtigen Rufnummer und dem Passwort kommt immer falsches Passwort.

**Comment by Ludy87** [comment]
Ich habe es mit Email Adresse und Telefonnummer getestet, zwei verschiedene Profile.

Irgendwie ist da noch der Wurm drin.

**Comment by gig0r0** [comment]
Hi,
Mit E-Mail Adresse geht ohne Probleme. Jedoch sind dort die ganzen Sensoren - abgesessen von XCoins nicht auslesbar.

**Comment by Ludy87** [comment]
Vielleicht eine dumme Frage, aber wo änderst du das Password?

**Comment by gig0r0** [comment]
Bei Xplora? Bei der App?
In Home assistant? In dem ich lösche und neu hinzufüge. Mit Mailadresse gehts ja genau so.

**Comment by Ludy87** [comment]
Ob du das Password in der App änderst oder woanders - Xplora.

**Comment by gig0r0** [comment]
In der App - im Web kann man sich ja irgendwie nicht wirklich irgendwo einloggen - jedenfalls habe ich nichts gefunden bisher. (Wir haben die Uhr seit Weihnachten)

**Comment by Ludy87** [comment]
Sorry, wenn ich so tief nachharke - ist nicht böse gemeint oder gegen deine Person, ich will nur verstehen wann und wie das Passwort eventuell falsch übertragen wird.

1. du loggst dich in die Android-App mit Telefonnummer und dem aktuellen Passwort ein
2. dann auf Einstellungen
3. Passwort ändern
4. altes Password
5. zwei mal das neue Password
6. speichern
7. und dann kommt die Meldung "Password erfolgreich geändert!"

![Screenshot 17 01 2023 20_45_56](https://user-images.githubusercontent.com/4592558/212997934-c61d6980-976e-41a3-8a78-d4c113a85939.png)

**Comment by gig0r0** [comment]
Genau so. ;)
Ich nehme dir das nicht übel, ich will das ja auch irgendwie gefixt bekommen. Ich denke immer, du denkst, ich bin doof. ;)

Aber ich mach es genau so. Seltsamerweise funktioniert der Login im Plugin mit der Mailadresse dann auch immer mit dem aktuellen Passwort. Nur eben nicht via Rufnummer - während ich in der App - nachdem ich mich ausgeloggt habe, auch mit der Rufnummer und dem neuen Passwort einloggen kann. Alles schon getestet.

Der Login mit der Mailadresse wäre ja völlig ausreichend - aber dort sieht man eben nur die Xcoins. 

Alles seltsam. Hat Xplora die API irgendwo veröffentlicht, so dass ich da selber mal via REST testen kann?

**Comment by Ludy87** [comment]
Keine offizielle API vorhanden, nur von mir zusammen gesucht: https://github.com/Ludy87/pyxplora_api

**Comment by Ludy87** [comment]
Die Registrierung wurde per Email oder mit der Telefonnummer von dir gemacht?

**Comment by gig0r0** [comment]
Das ist eine gute Frage. Wenn ich das wüsste - jedenfalls habe ich kurz vor Weihnachten einen Verification Code via E-Mail bekommen. Könnte also per Mail sein.
Mal Account komplett löschen und neu registrieren? ;)

**Comment by Ludy87** [comment]
Bin mir nicht sicher ob das hilft, auf eigene Gefahr würde ich dann sagen.

**Comment by gig0r0** [comment]
Würde ich morgen mal machen. Heute nicht mehr. ;)

**Comment by gig0r0** [comment]
Jetzt wird es verrückt.
Ich habe neuen Account erstellt. Eingerichtet.
Wollte mich damit einloggen - ging weder via Nummer, noch via Mail. Dann ging das Passwort, bei dem ich mir sicher bin, dass es richtig war, nicht mal mehr in der App.

Hab Passwort Recovery mit der App mit der Mobilfunkrufnummer gemacht. Passwort wieder eingestellt.

Nun kann ich mich mit Handynummer bei Home Assistant erfolgreich einloggen.
Und ich sehe die Uhr mit Firmware und allem drum und dran.

Ich habe das Gefühl, dass bei xplora ein Problem mit dem Daten lag…

**Comment by Ludy87** [comment]
Kann schon möglich sein. Die API ist nun auch nicht so das gelbe vom Ei.

Aber super das es jetzt klappt.
