### ISSUE TITLE
Markdown Sample🐛 

### ISSUE THREAD

**Issue by bluenazgul** [Ludy87/xplora_watch#155]
### What version of Integration has the issue?

2.6.1

### System Health details

Not needed

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I tried the Markdown Sample, only changed the sensor ro Match my one but Markdown stays empty

An 30 Seconds Automation to read the Messages is also created

### Reproduction steps

1. Copy Paste Markdown Sample,
2. edit Sensor
3. Created Automation to read Messages

### Debug logs

```text
None
```

**Comment by Ludy87** [comment]
@bluenazgul 
Have you tried a restart?

**Comment by bluenazgul** [comment]
I tried several restarts, sadly without a changing result

I See the Message Sensor changing, once the watch sends s Message, but thats all

**Comment by RestOp** [comment]
By the way, have also empty markdown...

**Comment by Ludy87** [comment]
@RestOp
@bluenazgul 

Check: https://github.com/Ludy87/xplora_watch/issues/185
