### ISSUE TITLE
QUESTION : Do I need to trigger Video / Image Downloads manually ?

### ISSUE THREAD

**Issue by siw1973** [Ludy87/xplora_watch#203]
### Is your feature request related to a problem? Please describe.

I can't raise an Issue, only raise feature request.....

### Describe the feature you want

Can you advise whether I need to manually initiate the Download Video / Image ?

Or how long do I need to leave it for images to be downloaded ?

**Comment by Ludy87** [comment]
Hi @siw1973 this must trigger the reading of the messages via automation or in the service itself.

https://github.com/Ludy87/xplora_watch/blob/main/samples/automation-read-messages.yaml

**Comment by siw1973** [comment]
Ahhhh..... I was going this was a Holy Grail of reading stored Videos/Images on the device.

If the watch is lost or broken then all of the images are lost.

My son takes pictures and videos with friends which aren't Sent via messages and just sit on the device.

I was hoping to extract them and store them so he can access them on other devices.
