### ISSUE TITLE
🐛 Charging / not charging does not seem to work

### ISSUE THREAD

**Issue by MartinVinter** [Ludy87/xplora_watch#211]
### Is your feature request related to a problem? Please describe.

First of all, thank you for creating the HA / explorer integration and for sharing it with the rest of us. You are awesome for doing that. 

This is more of a bug-repport I guess, but the only option I get when opening a new issue is to make a feature request.

It appears the Charging / not_charging sensor for xplorer doesn't work. Using it triggers an error that looks like this:
<img width="781" alt="image" src="https://github.com/Ludy87/xplora_watch/assets/61094818/89416459-8589-40e5-94b2-8ffe370b534c">

Notice that the sensor is also named differently than the others suggesting that something might be broken.

Hacs, HA and the plugin code are all updated to latest versions.

### Describe the feature you want

I'd like the charging / not charting states to be usable as automation triggers.

**Comment by Ludy87** [comment]
@MartinVinter https://github.com/home-assistant/core/issues/93317
