### ISSUE TITLE
Integration wird nicht angezeigt

### ISSUE THREAD

**Issue by thmnxo4** [Ludy87/xplora_watch#22]
Hi,
ich habe das Repo über HACS installiert.

configuration.yaml:

xplora_watch:
  country_code: "+49"
  phonenumber: "mynumber"
  password: "mypassword"
  userlang: "de-DE"
  timezone: "Europe/Berlin"
  watch_id: 
    - kidswatchid
  types:
    - "battery"
    - "xcoin"
    - "state"
    - "safezone"
    - "charging"
    - "silents"
    - "alarms"
    - "dt_watch"
  safezones: "show" 
  scan_interval: 180 
  tracker_scan_interval: 60 

Die Integration wird aber nicht angezeigt. Was ist hier nicht korrekt?
Watch ID ist korrekt.

**Comment by Ludy87** [comment]
Hi,

du musst bei der Benutzeroberfläche eine Karte hinzufügen und die entsprechenden Sensoren und binary Sensoren hinzufügen.

https://www.home-assistant.io/dashboards/#:~:text=To%20start%2C%20go%20to%20the,select%20a%20card%20to%20add.

Ansonsten findest du die Integration unter HACS-Integration

**Comment by thmnxo4** [comment]
Hi,

die Sensoren stehen mir ja gar nicht zur Auswahl.

Ludy ***@***.***> schrieb am Fr., 1. Apr. 2022, 04:21:

**Comment by maurcol** [comment]
I have the same issue. I added the integration via HACS and resterted HA after added the following to configuration.yaml

# Leo's watch
xplora_watch:
  country_code: "+358"
  phonenumber: "watchPhoneNumber"
  password: "password"
  userlang: "es-ES"
  timezone: "Europe/Helsinki"
  watch_id:
    - iPutHereTheIMEI
  types:
    - "battery"
    - "xcoin"
    - "state"
    - "safezone"
    - "charging"
    - "silents"
    - "alarms"
    - "dt_watch"
  safezones: "show"
  scan_interval: 180
  tracker_scan_interval: 60

After adding this I restarted HA again but when I went to Home Assistant » Developer Tools » States
There are not sensors for the watch. 
Also is the watch_id for the configuration.yaml the IMEI or is the name of the watch given in the xplora app?

**Comment by thmnxo4** [comment]
EID, 32 digits

**Comment by Ludy87** [comment]
@maurcol 

```yaml
watch_id:
- iPutHereTheIMEI
```

Please remove and activate the debug log.

**Comment by Ludy87** [comment]
@thmnxo4 bitte den Debug Log aktivieren und schauen welcher Fehler angezeigt wird.

**Comment by thmnxo4** [comment]
Exception: Child phonenumber not found!

**Comment by Ludy87** [comment]
@thmnxo4 dann Versuche es statt watch_id mit der child_phonenumber

**Comment by thmnxo4** [comment]
Funktioniert

**Comment by maurcol** [comment]
Added this and modify the config in configuration.yaml

# Leo's Smart watch
# Debug
logger:
  logs:
    custom_components.xplora_watch: debug
# Leo's watch
xplora_watch:
  country_code: "+358"
  phonenumber: "watchPhoneNumber"
  password: "password"
  userlang: "es-ES"
  timezone: "Europe/Helsinki"
  types:
    - "battery"
    - "xcoin"
    - "state"
    - "safezone"
    - "charging"
    - "silents"
    - "alarms"
    - "dt_watch"
  safezones: "show"
  scan_interval: 180
  tracker_scan_interval: 60


So I removed the watch_id! and added the debug log. Still not working.
Here is what the log from HA  says:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/xplora_watch/__init__.py:124
Integration: xplora_watch (documentation, issues)
First occurred: 3:17:42 PM (1 occurrences)
Last logged: 3:17:42 PM

Error during setup of component xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/xplora_watch/__init__.py", line 101, in async_setup
    success = success or await _setup_controller(hass, controller_config, config)
  File "/config/custom_components/xplora_watch/__init__.py", line 124, in _setup_controller
    await controller.init_async()
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 88, in init_async
    raise LoginError("Login to Xplora® API failed. Check your input!")
pyxplora_api.exception_classes.LoginError: Login to Xplora® API failed. Check your input! - 1

**Comment by Ludy87** [comment]
@maurcol add child_phonenumber

**Comment by maurcol** [comment]
Funktioniert, Danke

**Comment by Ludy87** [comment]
@maurcol 

please change your configuration

```yaml
xplora_watch:
    country_code: "+358"
    phonenumber: "watchPhoneNumber"
    password: "password"
    userlang: "es-ES"
    timezone: "Europe/Helsinki"
    child_phonenumber:
      - "watchPhoneNumber"
    types:
      - "battery"
      - "xcoin"
      - "state"
      - "safezone"
      - "charging"
      - "silents"
      - "alarms"
      - "dt_watch"
    safezones: "show"
    scan_interval: 180
    tracker_scan_interval: 60
```

**Comment by thmnxo4** [comment]
Die Integration sorgt für einen Logout der Xplora App. Gibt es da noch
einen Workaround für?



Ludy ***@***.***> schrieb am Fr., 1. Apr. 2022, 15:23:

**Comment by Ludy87** [comment]
@thmnxo4 ja, nimm die Uhr als Kontakt mit auf und logge dich mit der an.

Und bitte nächste Mal ein neues issues öffnen, danke
