### ISSUE TITLE
The location is not updated automatic anymore🐛

### ISSUE THREAD

**Issue by MrGlad8** [Ludy87/xplora_watch#228]
### What version of Integration has the issue?

v2.8.2

## System Information

version | core-2023.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 25, 2023 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.4
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 14.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.11.0), File editor (5.6.0), Home Assistant Google Drive Backup (0.111.1), Samba share (10.0.2), Terminal & SSH (9.7.1), ESPHome (2023.6.3), InfluxDB (4.7.0), Grafana (8.3.0), Studio Code Server (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 17
-- | --
resources | 17
views | 73
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 21, 2023 at 09:25
-- | --
current_recorder_run | July 1, 2023 at 10:57
estimated_db_size | 562.54 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Swedish Mail Delivery</summary>

Version | 1.0.7
-- | --
Idle | false
Instances | 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The clock wont update the location to me anymore per automatic. It do work if I use the Track Watch service though manually.

### Reproduction steps

1. I have installed the Xplora Watch integration as mentioned in the guide

### Debug logs

```text
2023-07-01 20:03:11.188 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] pyxplora_api lib version: 2.8.3-1298
```

**Comment by Ludy87** [comment]
Hi, does the error appear right at the beginning or later? I tested over the weekend and couldn't find anything.

**Comment by MrGlad8** [comment]
> Hi, does the error appear right at the beginning or later? I tested over the weekend and couldn't find anything.

Hey, well I dont know if its an error. But the clock wont update to HA automatically anymore. The xplora_watch.see do work though if I trigger that service!

**Comment by Ludy87** [comment]
@MrGlad8 check my preview version: https://github.com/Ludy87/xplora_watch/pull/253#issue-1868547742
