### ISSUE TITLE
Change devica class of steps counter

### ISSUE THREAD

**Issue by Jopand** [Ludy87/xplora_watch#244]
### Is your feature request related to a problem? Please describe.

Right now the steps sensor is an enum. This will not show historical. Alues in a graph, bit in a hardly readable enum state multicolored bar. By removing the device class and adding a unit of measurement, it will be shown nicely in a graph.

Replacing the device_class line with the following seems to work:
native_unit_of_measurement="steps",

### Describe the feature you want

-

**Comment by Ludy87** [comment]
@Jopand check my preview version: https://github.com/Ludy87/xplora_watch/pull/253#issue-1868547742
