### ISSUE TITLE
Integration unable to start after restart HA 🐛

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Ludy87/xplora_watch#245]
### What version of Integration has the issue?

2.8.3

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | aarch64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4610
Installed Version | 1.32.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 26

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 15, 2023 at 03:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 113.9 GB
disk_used | 54.3 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.12.4), Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), Advanced SSH & Web Terminal (15.0.6), Samba share (10.0.2), MariaDB (2.6.1), ESPHome (2023.7.1), Assistant Relay (0.7.4), Mosquitto broker (6.2.1), Zigbee2MQTT (1.32.2-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 16
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 29, 2023 at 21:46
-- | --
current_recorder_run | August 8, 2023 at 14:02
estimated_db_size | 1604.41 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 10 / 10
local_online | 10 / 10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

@Ludy87 After I restarted HA today the integration is not starting anymore, it looks also kind of similar to the following issue that also appears at me fornthe custom asus integration (while I already did do several restarts after update to HA 2023.8.1)

https://github.com/Vaskivskyi/ha-asusrouter/issues/609

### Reproduction steps

1. Restart HA

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/xplora_watch/coordinator.py:107
Integration: Xplora® Watch (documentation, issues)
First occurred: 14:03:51 (1 occurrences)
Last logged: 14:03:51

Error setting up entry Xplora® for xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xplora_watch/__init__.py", line 34, in async_setup_entry
    await coordinator.init()
  File "/config/custom_components/xplora_watch/coordinator.py", line 107, in init
    await self.controller.init(self.controller._gql_handler.getApiKey(), sec=self.controller._gql_handler.getSecret())
  File "/usr/local/lib/python3.11/site-packages/pyxplora_api/pyxplora_api_async.py", line 77, in init
    raise LoginError(self.error_message)
pyxplora_api.exception_classes.LoginError: The server is not responding, please wait a moment and try again.
```

**Comment by Ludy87** [comment]
The Xplora servers are currently unavailable - you can also check this via the app.

**Comment by smarthomefamilyverrips** [comment]
Hi @Ludy87 now I did see, sorry for open this bug as it did look similar to the ASUS one I not really did check the app first to see if are no problems on Xplora side. Thanks for your response!
