### ISSUE TITLE
[🏗️ FR] Ignore location if accuracy is not good

### ISSUE THREAD

**Issue by redvers76** [Ludy87/xplora_watch#28]
### Is your feature request related to a problem? Please describe.

Have set this up to get notified when my son leaves school and gets home. However, during lunch breaks when he is in the playground, I get notifications because the GPS sensitivity is 1500m and it thinks he has left the relevant school zone.

### Describe the feature you want

The ability to set a level of accuracy, and to ignore lat/long co-ordinates that are returned with a worse accuracy.

**Comment by Ludy87** [comment]
hi @redvers76 can you show me your ymal code, i don't quite understand the problem. It sounds like problems in the definition of the zone.

**Comment by redvers76** [comment]
Which yaml do you need to see? 

Zone is defined as a radius 65 around the school he attends. When I got the notification I logged into the Xplora app and it showed his position as being 1 mile away from the school, in the middle of a field. On the bottom of that page it said "GPS Accuracy: 1500m"

A few minutes later when it updated again, it showed him as being back at school. I don't know if the full history is stored in the sql database (i.e. including the full set of data captured) so I will set up logging tomorrow and and hopefully see if the same thing happens again.

Seems like someone has had a similar issue with the IOS app accuracy : https://github.com/home-assistant/iOS/issues/43

**Comment by Ludy87** [comment]
The accuracy results from the GPS signal and can neither be influenced by the app nor by my integration.
You can try to lower the interval, which then leads to high battery consumption.

**Comment by redvers76** [comment]
I am not asking for you to influence the accuracy. I am asking for you to ignore the lat/long if the accuracy is poor.

For example, this morning the map showed my son as being down the road. When looking at the details from the sensor I can see the device has dropped off the wifi so it is using cell tower location :

source_type: CELL
battery: 100
latitude: 52.478612
longitude: -0.709712
**radius: 1665**
country: United Kingdom
countryAbbr: gb
province: England
city: Corby
addr: Oakley Grange Adult Training Centre, Patrick Rd, Corby, NN18 9NP, UK
poi: School Bungalow
last Track: 2022-04-27T06:19:58.350277
Home Distance: 713 m
entity_picture: https://api.myxplora.com/file?id=1
icon: mdi:watch
friendly_name: Ped Watch Tracker 011

As you can see, because it is using cell location, the accuracy (radius) is quite large. The same can happen with GPS location; the returned radius is large because of poor signal at the point the request to track was made.

In the event that the sensor returns a radius >100 (for example) I know I cannot trust the latitude / longitude provided, especially when using critical alerts to notify mine and my wife's phone. Because the official map / zone functionality doesn't allow you to ignore certain readings (i.e. in the "leaving_zone" code ignore if accuracy is poor) the alternative is to not record the poor readings in the first instance to prevent false positives.

As such, what I would like the logic to do is something like :

```
get lat, lng, rad
if rad > configured_rad
   /* skip updating data */
else
    sensor.lat = lat
    sensor.lng = lng
    sensor.rad = rad
```

Hope this makes sense :)

**Comment by redvers76** [comment]
Having thought about this, I think the "ignore poor co-ordinates" logic should actually be part of "notify_leaving_zone.yaml" as opposed to the watch tracker. The tracker should always post the information it has, regardless of GPS sensitivity.

For this to be feasible, the output from xplora_watch needs to feed correctly into person entity. In my example above where source_type = CELL, it's missing the gps_accuracy field, and I have also seen it sometimes go missing on WIFI as well. However the radius is always present. Is there a change that can be made to always push radius as gps_accuracy so that it should always be available to the person entity?
