### ISSUE TITLE
Message cannot send

### ISSUE THREAD

**Issue by DIYtechie** [Ludy87/xplora_watch#358]
### What version of Integration has the issue?

2.13.0

### System Health details

![IMG_3953](https://github.com/Ludy87/xplora_watch/assets/20454469/bd4a1d6a-3f97-45c5-858e-6c722d31a54b)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

for some reason the message service does bot seem to work in this latest release 2.13.0? At least on my system. GPS tracking and reading messages still works.

![IMG_3952](https://github.com/Ludy87/xplora_watch/assets/20454469/a9ccb2ce-0c17-4564-8391-0f98bd182dcf)

### Reproduction steps

Try and send a message via the send message service and check the logs

### Debug logs

```text
![IMG_3952](https://github.com/Ludy87/xplora_watch/assets/20454469/a9ccb2ce-0c17-4564-8391-0f98bd182dcf)
```

**Comment by Ludy87** [comment]
Hi @DIYtechie Can you send the complete log, there is important information in it, select what belongs to the integration. Thanks

**Comment by DIYtechie** [comment]
Sorry for the delay, but it takes a lot of time to clean the log. log attached. 
[home-assistant_xplora_watch_2024-01-23T21-21-09.415Z.log](https://github.com/Ludy87/xplora_watch/files/14047320/home-assistant_xplora_watch_2024-01-23T21-21-09.415Z.log)

**Comment by Ludy87** [comment]
This is not a fix, just to better analyze the error.
