### ISSUE TITLE
[🏗️ FR]  watch into automations - specific areas

### ISSUE THREAD

**Issue by MrGlad8** [Ludy87/xplora_watch#36]
### Is your feature request related to a problem? Please describe.

Yes I want to add the watch into automations that updates me when it enters specific areas. And for that I need it to appear as a Device. But it's not shown in the device list. Can this be fixed somehow?

### Describe the feature you want

Yes I want to add the watch into automations that updates me when it enters specific areas. And for that I need it to appear as a Device. But it's not shown in the device list. Can this be fixed somehow?

**Comment by Ludy87** [comment]
can you give me an example, i need information which functions of the watch are needed.
