### ISSUE TITLE
[🐛 BUG] cannot start integration

### ISSUE THREAD

**Issue by th00mas88** [Ludy87/xplora_watch#39]
### System Health details

Version | core-2022.6.1
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Does not work - I followed instructions and seems to not work as expected.

As seen in log it askes to check input, im not sure which part of the input I should be looking at

### Reproduction steps

my config - 

xplora_watch:
  country_code: +46
  phonenumber: 7##########
  password: MYPARENTACCOUNTPASSWORD
  userlang: en-GB
  child_phonenumber:
   -  7##########
  timezone: Europe/Berlin
  types:
    - battery
    - xcoin
    - syate
    - safezone
    - charging
    - silents
    - alarms
    - dt_watch
  safezones: "show" 
  scan_interval: 180 # default sec - optional
  tracker_scan_interval: 60 # default sec - optional

### Debug logs

```text
Error during setup of component xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/xplora_watch/__init__.py", line 109, in async_setup
    success = success or await _setup_controller(hass, controller_config, config)
  File "/config/custom_components/xplora_watch/__init__.py", line 132, in _setup_controller
    await controller.init()
  File "/usr/local/lib/python3.9/site-packages/pyxplora_api/pyxplora_api_async.py", line 80, in init
    raise LoginError("Login to Xplora® API failed. Check your input!")
pyxplora_api.exception_classes.LoginError: Login to Xplora® API failed. Check your input! - 1
```

**Comment by Ludy87** [comment]
these are the relevant settings
```yaml
xplora_watch:
  country_code: "+49"
  phonenumber: "123456789"
  password: "password"
  userlang: "de-DE"
  timezone: "Europe/Berlin"
```
Your debug information is not complete, please give me the version number of the integration

Use the instructions: https://github.com/Ludy87/xplora_watch/issues/24

**Comment by th00mas88** [comment]
Ah sorry 

Running v1.0.41

**Comment by th00mas88** [comment]
Hi - 

To follow up Its still not working 

I reduced to the smaller config  (Note i kept language settings and location . and the password is with an @ if that makes a difference ) 

xplora_watch:
  country_code: "+46"
  phonenumber: "7#########"
  password: ##########@
  userlang: "de-DE"
  timezone: "Europe/Berlin"
