### ISSUE TITLE
Setup failed with HA 2024.4.3

### ISSUE THREAD

**Issue by sevorl** [Ludy87/xplora_watch#401]
### What version of Integration has the issue?

2.13.7

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4622
Installed Version | 1.34.0
Stage | running
Available Repositories | 1484
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 116.7 GB
disk_used | 45.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (17.0.11), File editor (5.8.0), Terminal & SSH (9.13.0), NGINX Home Assistant SSL proxy (3.9.0), Duck DNS (1.16.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.3.1), Bookstack (2.0.3), Nginx Proxy Manager (1.0.1), deCONZ (6.23.0), AdGuard Home (5.0.6), AppDaemon (0.16.4), Vaultwarden (Bitwarden) (0.21.2), ESPHome (2024.3.2), SQLite Web (4.1.2), Advanced SSH & Web Terminal (17.2.0), Mosquitto broker (6.4.0), phpMyAdmin (0.9.1), Cloudflared (5.1.8), MariaDB (2.6.1), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 39
views | 42
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6. April 2024 um 07:44
-- | --
current_recorder_run | 12. April 2024 um 16:00
estimated_db_size | 1243.00 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After updating HA to 2024.4.3, Xplora does not start:
Logger: homeassistant.setup
Quelle: setup.py:273
Erstmals aufgetreten: 16:03:27 (1 Vorkommnisse)
Zuletzt protokolliert: 16:03:27

Setup failed for custom integration 'xplora_watch': Requirements for xplora_watch not found: ['aiohttp==3.9.3', 'pyxplora_api==2.12.6'].

### Reproduction steps

1. Update HA to 2024.4.4
2. Xplora does not start

### Debug logs

```text
Logger: homeassistant.setup
Quelle: setup.py:273
Erstmals aufgetreten: 16:03:27 (1 Vorkommnisse)
Zuletzt protokolliert: 16:03:27

Setup failed for custom integration 'xplora_watch': Requirements for xplora_watch not found: ['aiohttp==3.9.3', 'pyxplora_api==2.12.6'].
```

**Comment by seebaer1976** [comment]
I have exactly the same error message

**Comment by jgrob1** [comment]
> I have exactly the same error message

And me. Although to be fair, I just tried to set it up for the first time - Unsuccessfully, but possibly only because of this error.

**Comment by IamMattM** [comment]
Same problem as well form e this morning:

`Setup failed for custom integration 'xplora_watch': Requirements for xplora_watch not found: ['aiohttp==3.9.3', 'pyxplora_api==2.12.6'].`
