### ISSUE TITLE
Xplora WAtch and Device Tracker

### ISSUE THREAD

**Issue by MartinAM80** [Ludy87/xplora_watch#46]
Hello.
Sorry if this is a stupid question, but I can't figure out how to het HA to show tracker status Home / Away / Other Zones.

Please could you provide more guide on how to get it to work?

Regards,
Martin

**Comment by westis** [comment]
If you filter entities by watch at Developet Tools/State, you see the watch tracker with a zone as the state? If you have set up zones in /config/zones the watch should recognize when it is inside one of those zones, at least that works for me.

And then I use the map in a dashboard. Works also to use the Device card to select the watch tracker for my childrens watches to get the zone they are in.

**Comment by hmdrmch** [comment]
I'm struggling with the tracker status too. Sometimes it finds the right zone, but most often it just states as not_home (or Out)

@westis - Have you configured all of your zones in the configuration.yaml? Or have you added them through GUI?

**Comment by westis** [comment]
> @westis - Have you configured all of your zones in the configuration.yaml? Or have you added them through GUI?

Only via the GUI. But I haven't used it for more than a couple of days and it seems the location sometimes doesn't update for a few hours and the battery level often reports -1.

**Comment by MartinAM80** [comment]
I have investigated and I found that binary watch safe zone is showing as On but I the watch has 2 safezones:  Home and School.
So that is not possible to see which safezone the watch is in. 
![image](https://user-images.githubusercontent.com/46328195/186840922-e8ce7030-ebd3-4a4f-bf31-f01d59c3778b.png)

**Comment by westis** [comment]
@MartinAM80 But you can set up zones in Home Assistant and see what zone the watch is in. 

However, my problem is that the watches are very unreliable in updating their position. Sometimes it can take hours before they update, not sure why.
