### ISSUE TITLE
[🐛 BUG] Tracking does not work if device_tracker is bound to person

### ISSUE THREAD

**Issue by ravor-org** [Ludy87/xplora_watch#55]
### System Health details

<html><body>

Version | core-2022.9.5
-- | --
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
User | homeassistant
Virtual Environment | true
Python Version | 3.10.6
Operating System Family | Linux
Operating System Version | 5.4.70-ravor
CPU Architecture | x86_64
Timezone | Europe/Berlin
Configuration Directory | /home/homeassistant/.homeassistant

</body>
</html>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Hi,

in my HA instance all trackable users are configured as persons (as in "settings" -> "people"). For some reason, the person is always displayed as "unknown" or "away" instead of the location. Even in a map card, the person is not displayed. If I choose to use the device tracker entity directly, it is displayed as it should.

Could you check that?

### Reproduction steps

1. Create a person in "settings" -> "people"
2. Associate the device_tracker entity from the watch to the person
3. Add person to UI or to map card

Expected outcome:
Person should be displayed like device_tracker entity

Actual outcome:
Person does not have a location

### Debug logs

```text
Data is fetched:
Sep 19 12:57:30 hwr-server01 hass[11602]: 2022-09-19 12:57:30.380 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Fetch data from Xplora®: 6983592
Sep 19 12:57:30 hwr-server01 hass[11602]: 2022-09-19 12:57:30.686 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] load address from openstreetmap.org
Sep 19 12:57:30 hwr-server01 hass[11602]: 2022-09-19 12:57:30.686 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Finished fetching xplora_watch-34051 data in 2.686 seconds (success: True)
```

**Comment by ravor-org** [comment]
Heres a picture, how it looks on my UI:
![grafik](https://user-images.githubusercontent.com/10080228/191004268-c2c8820f-eafa-4f98-84b5-4d7891a72984.png)

That's how it looks on UI:
1. Person with device_tracker attached (always displays unknown)
2. device_tracker entity directly shown
3. Person with another (working) device_tracker attached (google maps)
4. Google maps device tracker directly shown

**Comment by Ludy87** [comment]
Hi, this is not a bug, just not implemented
