### ISSUE TITLE
[🏗️ FR] Travel time not working - showing unknown

### ISSUE THREAD

**Issue by ravor-org** [Ludy87/xplora_watch#58]
### Is your feature request related to a problem? Please describe.

After adding the functionality for home / not_home state - Thank you very much for that - I tried to use the Google Travel Time together with the person (which only has Xplora attached to it) or with the device tracker but it still shows unknown as it seems to be unable to get the coordinates for the Xplora entities.

### Describe the feature you want

I want to use the Google Travel Time together with the Xplora entities, but it seems, that this is not implemented either.

![grafik](https://user-images.githubusercontent.com/10080228/191252822-efc34094-2221-41e0-8909-d5e2db27b211.png)

**Comment by Ludy87** [comment]
Hi @ravor-org , it works for me and is also displayed correctly.

![google_travel_time](https://user-images.githubusercontent.com/4592558/191285349-86c49ddb-e342-4d60-88e9-487e796780e4.png)

**Comment by ravor-org** [comment]
I've tried that again and even enabled debugging for google_travel_time and in my case it looks different.

Heres the log from travel integration:
`Sep 21 10:31:38 hwr-server01 hass[28207]: 2022-09-21 10:31:38.121 DEBUG (SyncWorker_0) [homeassistant.components.google_travel_time.sensor] Getting update for origin: not_home destination: 52.5685,13.8941`

It does not matter, if device or person is used as origin. I'm not sure, what causes the origin to be displayed as "not_home" as the coordinates are displayed correctly in the map.

![grafik](https://user-images.githubusercontent.com/10080228/191457726-1f3782e7-2494-44ef-a57f-4d8143aefb9c.png)
![grafik](https://user-images.githubusercontent.com/10080228/191458011-a96649f7-9a81-49b0-b6eb-9cbec036ec44.png)
![grafik](https://user-images.githubusercontent.com/10080228/191458359-b1a2bc78-b8c8-4722-9f14-e536393e293d.png)

**Comment by ravor-org** [comment]
I've enabled debugging and somehow home-assistant thinks, that the "not_home" is a nested entity:
`Sep 21 11:15:00 hwr-server01 hass[3135]: 2022-09-21 11:15:00.007 DEBUG (SyncWorker_7) [homeassistant.helpers.location] Getting nested entity for state: not_home`

But as this is no nested entity, it is not resolved and therefore inaccessible.

**Comment by ravor-org** [comment]
I've created a pull request (as a quick fix): #59 

Maybe you could also change the underlying API lib to maintain the type.
