### ISSUE TITLE
🏗️ Enable "unknown" state if watch is offline

### ISSUE THREAD

**Issue by ravor-org** [Ludy87/xplora_watch#66]
### Describe the feature you want

In version 1 of the integration, the device_tracker had 2 state groups: zone/away/home and unknown. In version 2 this "feature" has gone missing. The PR #65 tries to address this problem by setting latitude and longitude to "None" if watch is offline.

**Comment by Ludy87** [comment]
The "unknown" state is shown here when the watch is offline.

https://github.com/Ludy87/xplora_watch/blob/8016ae863fe1f7cf1465e3e447a45d29ef9cc657/custom_components/xplora_watch/device_tracker.py#L164

**Comment by ravor-org** [comment]
Yes and no, if person integration is fully used like in #63, then it doesn't work anymore. Unfortunately (at least in my case) the watch is always returning "WIFI" as source type and this interferes with the person integration I'm using everywhere.

**Comment by Ludy87** [comment]
you can solve this with:
```python
locateType = return self._coordinator.watch_entry[self.watch_uid]["locateType"] 
if locateType == wifi or locateType == gps: 
   return SourceType.GPS
else:
  return locateType  
 ```
