### ISSUE TITLE
🏗️ Add service to update watch location/other information on demand

### ISSUE THREAD

**Issue by lakofsth** [Ludy87/xplora_watch#72]
### Is your feature request related to a problem? Please describe.

The update interval defaults to 180 seconds, which unfortunately appears to cause accelerated battery drain on the device as it is polled at the interval. I have increased the default interval to save battery, but this means that some automations will be delayed (e.g. arriving home, disarming routines activated when out of the home).

### Describe the feature you want

I would like a service I can call in HA to request an update to the location/other information for a specific watch.

Use-case: presence is detected at home, but no watch device is detected in the zone. This triggers an update for the watch location, which then triggers other actions related to person(s) being at home.

Use-case: guardian wants to know where their child is, but without adjusting the update frequency for the integration.

**Comment by Ludy87** [comment]
Hi @lakofsth, I did some experimenting and came to this solution. It's not the best, unfortunately, as it polls all clocks.

Maybe @ravor-org has another suggestion or idea.

**Comment by lakofsth** [comment]
Thanks for the quick response! I'll try it out. I only have one watch so this satisfies my needs fully.

**Comment by ravor-org** [comment]
I indeed have a suggestion: we could use the update method (service: homeassistant.update_entity) and force a update like with the just implemented service.

**Comment by Ludy87** [comment]
with an automation I have it in the test. I just can't differentiate between two watches. Every attempt failed.

**Comment by Ludy87** [comment]
```yaml
alias: See Watch
description: ""
trigger:
  - platform: time
    at: "14:15:00"
condition: []
action:
  - service: xplora_watch.see
    data: {}
mode: single

```
