### ISSUE TITLE
Integration not updating entities

### ISSUE THREAD

**Issue by hauard** [Ludy87/xplora_watch#87]
## System Information

version | core-2022.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4933
Installed Version | 1.28.2
Stage | running
Available Repositories | 1123
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 28.6 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Node-RED (13.4.0), SSH & Web Terminal (12.0.2), Home Assistant Google Drive Backup (0.108.4), File editor (5.4.1), Glances (0.16.0), Log Viewer (0.14.0), Mosquitto broker (6.1.3), Let's Encrypt (4.12.7), NGINX Home Assistant SSL proxy (3.1.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18. oktober 2022 kl. 02:12
-- | --
current_recorder_run | 18. oktober 2022 kl. 17:25
estimated_db_size | 4.87 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Xplora integration installs and configures without issues, but the entities does not update. The watch is on, online, and have been working earlier. It was also working for some time after the integration got it's own UI in "Integrations." Have been trying login with phone number and email, both seem to be acceptet, but not updating.
![xplora](https://user-images.githubusercontent.com/112585314/196593936-952861af-1b59-4589-aac1-03f02b69d9f8.png)

Have tried to reinstall the integration, removing the installation in HACS, restarting HA between every (un)install, and rebooting host numerous times.

After enabling debug-mode, I get server-connect timeout, see attachment.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Logger: custom_components.xplora_watch.coordinator
Source: custom_components/xplora_watch/coordinator.py:64
Integration: Xplora® Watch (documentation, issues)
First occurred: 03:03:02 (1 occurrences)
Last logged: 03:03:02

Unexpected error fetching xplora_watch-864 data: Cannot connect to the server. -
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/xplora_watch/coordinator.py", line 68, in _async_update_watch_data
    await self.init()
  File "/config/custom_components/xplora_watch/coordinator.py", line 64, in init
    await self.controller.init(True)
  File "/usr/local/lib/python3.10/site-packages/pyxplora_api/pyxplora_api_async.py", line 86, in init
    raise LoginError(self.error_message)
pyxplora_api.exception_classes.LoginError: Cannot connect to the server. -
```

**Comment by Ludy87** [comment]
Hi @hauard it looks like the server is being worked on. Because also have the error in the log. Maintenance work is scheduled for Saturday. Maybe that's the preparation for it.

![Screenshot_20221019-074715](https://user-images.githubusercontent.com/4592558/196607642-8239b2ac-6304-4c93-b17b-def694741483.png)

**Comment by hauard** [comment]
Do you still have this error? Saw another issue about the API might have changed? We have to use an admin-account?

**Comment by Ludy87** [comment]
Hi, it works with an admin account. There was maintenance work over the weekend, I hope that they will update the API soon.

**Comment by MrGlad8** [comment]
well this integration doesnt work since the last update :( Worked fine before. Now there's no contact with the watch anymore. Sad!

**Comment by Ludy87** [comment]
@MrGlad8 currently it is only possible with an admin account. we hope that xplora changes this

**Comment by hauard** [comment]
Can confirm integration works with admin account. Also, I have not been logged out of the Xplora app on my phone, despite using that admin account in the integration.

**Comment by eirikgrindevoll** [comment]
> Can confirm integration works with admin account. Also, I have not been logged out of the Xplora app on my phone, despite using that admin account in the integration.

Anyone else can confirm this? Not logged out?

**Comment by Ludy87** [comment]
> > Can confirm integration works with admin account. Also, I have not been logged out of the Xplora app on my phone, despite using that admin account in the integration.
> 
> Anyone else can confirm this? Not logged out?

No, I can't confirm
