### ISSUE TITLE
Admin Account required 🐛 (bug summary)

### ISSUE THREAD

**Issue by bluenazgul** [Ludy87/xplora_watch#88]
### System Health details

Not needed

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I created a Account for thebwatch itself for HA

But since a few Updates i cant get Infos except Steos from the Watch anymore.

After delete and reinstall with Watch Admin Account i get Data, with an non Admin Account i dont get Data anymore

### Reproduction steps

1. Setup with non Admin Account
2. = no data, only Steps
3. Remove Device
4. Setup with Admin Account
5. = full data 

### Debug logs

```text
Not needed
```

**Comment by Ludy87** [comment]
info: https://github.com/Ludy87/xplora_watch/issues/24#issuecomment-1270090147
